spring:
  application:
    name: demo

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password:
      database: 0
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: true

grpc:
  server:
    port: 9091

app:
  api:
    kakao:
      key: ${APP_API_KAKAO_KEY:}

jwt:
  secret: ${JWT_SECRET:F0yB5JUd9/gAE2egZg09KmpnZA0KVFhMtxqiMIcYLu4nDOhR9K2zNhJoz0tKU6E3qOlQkc752ycdFee76i33gg==}
  access-token-expiration-time: 1209600000 # 14 day = 14 * 1000 * 60 * 60 * 24
  refresh-token-expiration-time: 15552000000 # 180day