name: swagger openapi extract
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Generate OpenAPI spec
        run: ./gradlew clean generateOpenApiDocs

      - name: Swagger UI Action
      - uses: Legion2/swagger-ui-action@v1.3.0
        with:
          output: swagger-ui
          spec-file: build/openapi.json
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: swagger-ui